#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE ROLE fedora LOGIN PASSWORD '$FEDORA_DB_PASSWORD';
  CREATE DATABASE fedora WITH ENCODING='UTF8';
  GRANT ALL PRIVILEGES ON DATABASE fedora TO fedora;
EOSQL
